name: "Map dictionary keys or values"
description: "Map dictionary keys or values based on the provided mapping or regex"

inputs:
  dictionary:
    description: "The dictionary containing the values to map. Must be valid JSON containing key-value pairs"
    required: true
  key-filter:
    description: "Regex filter to select the keys whose values should be mapped; map all values otherwise"
    required: false
  key-transform:
    description: "Map keys by applying the provided regex. Must contain one capturing group"
    required: false
  value-map:
    description: "The mapping of the current values to the new values as key-value pairs delimited by '|' or newlines"
    required: false

outputs:
  values:
    description: "The mapped key-value pairs"
    value: ${{ steps.map.outputs.values }}

runs:
  using: composite
  steps:
    - name: Parse value map
      id: value-map
      uses: govuk-one-login/github-actions/parse-parameters@oj-2738-test-harness-actions
      with:
        parameters: ${{ inputs.value-map }}
        json-output: true

    - name: Map values
      id: map
      shell: bash
      env:
        DICTIONARY: ${{ inputs.dictionary }}
        KEY_FILTER: ${{ inputs.key-filter }}
        KEY_TRANSFORM: ${{ inputs.key-transform }}
        VALUE_MAP: ${{ steps.value-map.outputs.parsed-parameters }}
        MAP: ${{ github.action_path }}/map-dictionary.sh
      run: echo values="$($MAP)" >> "$GITHUB_OUTPUT"
