version = 0.1
[default.deploy.parameters]
stack_name = "test-harness"
resolve_s3 = true
s3_prefix = "test-harness"
region = "eu-west-2"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = [
    "CodeSigningConfigArn=none",
    "PermissionsBoundary=none",
    "CriIdentifier=/common-cri-parameters/CriIdentifier",
    "TxmaStackName=txma-infrastructure",
    "Environment=dev",
]
image_repositories = []
tags = [
    "cri:deployment-source=manual",
    "cri:stack-type=dev",
    "cri:component=ipv-cri-common-test-harness"
]