name: Check PR

on: pull_request
permissions: {}

jobs:
  code-quality:
    name: Code quality
    uses: ./.github/workflows/code-quality.yml

  unit-tests-ts:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-ts.yml

  unit-tests-java:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-java.yml

  pact-tests-java:
    name: Pact tests
    strategy:
      fail-fast: false
      matrix:
        cri-provider: ["PassportTokenProvider","DrivingLicenceTokenProvider","FraudTokenProvider","AddressCriTokenProvider"]
    uses: ./.github/workflows/run-pact-tests-java.yml
    with:
      cri-provider: ${{ matrix.cri-provider }}
    secrets:
      pact-broker-host: ${{ secrets.PACT_BROKER_HOST }}
      pact-broker-username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact-broker-password: ${{ secrets.PACT_BROKER_PASSWORD }}

  pact-tests-ts:
    name: Pact tests
    strategy:
      fail-fast: false
      matrix:
        cri-provider: ["ExperianKbvCriTokenProvider","NinoCriTokenProvider"]
    uses: ./.github/workflows/run-pact-tests-ts.yml
    with:
      cri-provider: ${{ matrix.cri-provider }}
    secrets:
      pact-broker-host: ${{ secrets.PACT_BROKER_HOST }}
      pact-broker-username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact-broker-password: ${{ secrets.PACT_BROKER_PASSWORD }}

  deploy:
    name: Preview
    uses: ./.github/workflows/deploy-branch.yml
    permissions:
      id-token: write
      contents: read

  integration-tests:
    name: Run tests
    needs: deploy
    uses: ./.github/workflows/run-integration-tests.yml
    with:
      aws-region: ${{ needs.deploy.outputs.aws-region }}
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      stack-outputs: ${{ needs.deploy.outputs.stack-outputs }}
    secrets:
      api-gateway-api-key: ${{ secrets.APIGW_API_KEY }}
      ipv-core-stub-basic-auth-user: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_USER }}
      ipv-core-stub-basic-auth-pwd: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_PASSWORD }}
