name: Check test resources PR

on: 
  pull_request:
    paths:
      - 'test-resources/**'
      - '.github/**'

permissions: {}

jobs:
  code-quality:
    name: Code quality
    uses: ./.github/workflows/code-quality.yml
    permissions:
      packages: read
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-test-resources:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-test-resources.yml
    permissions:
      packages: read
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}

  test-resources-preview:
    name: Preview Test Resources
    uses: ./.github/workflows/test-resources-preview.yml
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}
