name: Check test resources PR

on: 
  pull_request:
    paths:
      - 'test-resources/**'
      - '.github/**'

permissions: {}

jobs:
  code-quality:
    name: Code quality
    uses: ./.github/workflows/code-quality.yml
    permissions:
      packages: read
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}

  # Branch setting require us to run all unit tests on all PRs
  unit-tests-ts:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-ts.yml
    with:
      coverage-report: true

  unit-tests-java:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-java.yml

  unit-tests-test-resources:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-test-resources.yml
    permissions:
      packages: read
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}

  test-resources-preview:
    name: Preview Test Resources
    uses: ./.github/workflows/test-resources-preview.yml
    permissions:
      id-token: write
      contents: read
      packages: read
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}

  integration-tests:
    name: Run tests
    needs: test-resources-preview
    uses: ./.github/workflows/run-integration-tests-test-resources.yml
    permissions:
      id-token: write
      contents: read
      packages: read
    with:
      aws-region: ${{ needs.test-resources-preview.outputs.aws-region }}
      stack-name: ${{ needs.test-resources-preview.outputs.stack-name }}
      stack-outputs: ${{ needs.test-resources-preview.outputs.stack-outputs }}
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}