name: Clean up deployments
run-name: Delete stale deployments

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am
    - cron: "0 10 * * 1-5"

permissions:
  id-token: write
  contents: read

concurrency: cleanup-dev-${{ github.head_ref || github.ref_name }}

jobs:
  delete-stacks:
    name: Delete stale stacks
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Get stale preview stacks
        uses: govuk-one-login/github-actions/sam/get-stale-stacks@cf644c0d66c41259bfe2509852d1211e3f01f44d
        with:
          threshold-days: 14
          stack-name-filter: preview-common-lambdas
          stack-tag-filters: |
            cri:deployment-source=github-actions
            cri:stack-type=preview
          description: preview
          env-var-name: STACKS

      - name: Delete stacks
        if: ${{ env.STACKS != null }}
        uses: govuk-one-login/github-actions/sam/delete-stacks@cf644c0d66c41259bfe2509852d1211e3f01f44d
        with:
          stack-names: ${{ env.STACKS }}
          verbose: true
