name: Dependency Submission (Java 17) 
#This workflow can be removed when we use Gradle 8+

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Submit Gradle dependencies
        uses: gradle/actions/dependency-submission@v4
        with:
          gradle-version: 7.5.1