name: Package test resources

on:
  workflow_dispatch:
  push:
    branches: [main, oj-2738-test-resources-gha]
#    paths: [test-resources/**]

permissions: {}

jobs:
  build:
    name: Build SAM app
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
      cache-restore-keys: ${{ steps.build.outputs.cache-restore-keys }}
    steps:
      - name: Build SAM application
        id: build
        uses: govuk-one-login/github-actions/sam/build-application@c9c3f2ef04d9145894de83e973b0f4dc1e90d14e
        with:
          template: test-resources/infrastructure/template.yaml
          source-dir: test-resources/**/lambdas/src
          cache-name: test-resources
          pull-repository: true

  publish-dev:
    needs: build
    name: Publish to dev
    uses: ./.github/workflows/package-for-deployment.yml
    with:
      cris: ADDRESS CHECK_HMRC
      environment: test-resources-dev
      cache-key: ${{ needs.build.outputs.cache-key }}
      cache-restore-keys: ${{ needs.build.outputs.cache-restore-keys }}
    permissions:
      id-token: write
      contents: read

  publish-build:
    needs: build
    name: Publish to build
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/package-for-deployment.yml
    with:
      cris: ADDRESS CHECK_HMRC
      environment: test-resources-build
      cache-key: ${{ needs.build.outputs.cache-key }}
      cache-restore-keys: ${{ needs.build.outputs.cache-restore-keys }}
    permissions:
      id-token: write
      contents: read
