name: Typecript checks
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./lambdas        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.*
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint