name: Unit pact tests (TypeScript)

on:
  workflow_call:
    inputs:
      cri-provider: {required: true, type: string}
    secrets:
      pact-broker-host: {required: true}
      pact-broker-username: {required: true}
      pact-broker-password: {required: true}

concurrency:
  group: pact-tests-ts-${{ inputs.cri-provider }}-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  run-pact-tests:
    name: TypeScript
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: lambdas
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:contract:ci
        env:
          CRI_UNDER_TEST: ${{ inputs.cri-provider }}
          PACT_BROKER_HOST: ${{ secrets.pact-broker-host }}
          PACT_BROKER_USERNAME: ${{ secrets.pact-broker-username }}
          PACT_BROKER_PASSWORD: ${{ secrets.pact-broker-password }}

