name: Unit pact tests

on:
  workflow_call:
    inputs:
      CRI_UNDER_TEST: { required: true, type: string }
    secrets:
      github-token: { required: true }
      pact-broker-host: { required: true }
      pact-broker-username: { required: true }
      pact-broker-password: { required: true }

concurrency:
  group: pact-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: { }

jobs:
  run-pact-tests:
    name: Java
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-common-lambdas-java-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-common-lambdas-java-
          path: |
            **/*/build/
            !**/*/build/jacoco
            !**/*/build/reports

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          PACT_BROKER_HOST: ${{ secrets.pact-broker-host }}
          PACT_BROKER_USERNAME: ${{ secrets.pact-broker-username }}
          PACT_BROKER_PASSWORD: ${{ secrets.pact-broker-password }}
          CRI_UNDER_TEST: ${{ inputs.CRI_UNDER_TEST }}
        run: ./gradlew pactTests jacocoTestReport --build-cache --parallel -x spotlessApply -x spotlessCheck
