name: Unit pact tests (TypeScript)

on:
  workflow_call:
    inputs:
      cri-provider: {required: true, type: string}
    secrets:
      pact-broker-host: {required: true}
      pact-broker-username: {required: true}
      pact-broker-password: {required: true}

concurrency:
  group: pact-tests-ts-${{ inputs.cri-provider }}-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  run-pact-tests:
    name: TypeScript
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci --include-workspace-root

      - name: Run tests
        uses: govuk-one-login/github-actions/node/run-script@e6b6ed890b35904e1be79f7f35ffec983fa4d9db
        env:
          CRI_UNDER_TEST: ${{ inputs.cri-provider }}
          PACT_BROKER_HOST: ${{ secrets.pact-broker-host }}
          PACT_BROKER_USERNAME: ${{ secrets.pact-broker-username }}
          PACT_BROKER_PASSWORD: ${{ secrets.pact-broker-password }}
        with:
          working-directory: lambdas
          script: npm run test:contract:ci
