name: Unit tests (Test Resources)

on:
  workflow_call:
    inputs:
      coverage-report: { type: boolean, required: false, default: false }
      coverage-artifact: { type: string, required: false, default: coverage-test-resources }
    outputs:
      coverage-artifact:
        value: ${{ inputs.coverage-artifact }}

concurrency:
  group: unit-tests-test-resources-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: { }

jobs:
  run-unit-tests:
    name: Test Resources
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-resources
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: test-resources/package.json

      - name: Install dependencies
        run: (cd .. && npm ci)

      - name: Run tests
        run: npm run test:coverage -- --config jest.config.ci.ts

      - name: Archive coverage results
        if: ${{ inputs.coverage-report }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage-artifact }}
          path: test-resources/coverage/lcov.info
          retention-days: 3
